trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: 'yy'  # Your connection name here

- script: |
    # List repositories in the registry
    docker search group15acr.azurecr.io/
    echo "Connection test successful!"
  displayName: 'Test ACR Connection'