trigger:
- main  # Triggers when changes are pushed to main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Docker registry service connection - replace with your connection name
  dockerRegistryServiceConnection: 'yy'
  imageRepository: 'group15-lab4'
  containerRegistry: 'group15acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Azure Web App - replace with your values
  webAppName: 'Webappgrp15'
  resourceGroupName: 'group15-resources'
  azureSubscription: 'Your-Azure-Subscription'

stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to Web App
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        resourceGroupName: $(resourceGroupName)
        containers: $(containerRegistry)/$(imageRepository):$(tag)
        appSettings: |
          -WEBSITES_PORT 8080