name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: group15acr.azurecr.io
        username: group15acr
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          group15acr.azurecr.io/group15-lab4:latest
          group15acr.azurecr.io/group15-lab4:${{ github.sha }}
    
    - name: Trigger Azure Pipeline
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/HAMKGroup15/Lab4
        azure-pipeline-name: 'Deploy-WebApp'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
